language: r

cache: packages

matrix:
  include:
    - os: osx
      r: release
    - os: linux
      r: release
      addons:
        apt:
          packages: ['valgrind']

env:
  global:
    - r_build_args="--no-build-vignettes --no-manual"
    - r_check_args="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

r_packages:
  - covr
  - rmarkdown
  - testthat
  - lintr
  - Rcpp
  - BH

bioc_packages:
  - BiocCheck

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  - R CMD BiocCheck $PKG_TARBALL
  - Rscript -e "devtools::install_github('dirmeier/datastructures')"
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      R -d "valgrind --tool=memcheck --leak-check=full --track-origins=yes" --vanilla < datastructures.Rcheck/datastructures-Ex.R
    fi
